#!/bin/sh
#TAP interface will be passed in $1

bridge=br0
guest_device=$1
echo "start script"
ifconfig $guest_device 0.0.0.0 up
echo "ifconfig done"
brctl addif $bridge $guest_device
echo "script done"